import type { KeywordTokenType, LiteralTokenType, UnitLiteralToken } from "./token";

export const keywords = new Map<string, KeywordTokenType | UnitLiteralToken["type"]>() // without identifier
keywords.set("and", "AND")
keywords.set("class", "CLASS")
keywords.set("else", "ELSE")
keywords.set("false", "FALSE")
keywords.set("fun", "FUN")
keywords.set("for", "FOR")
keywords.set("if", "IF")
keywords.set("nil", "NIL")
keywords.set("or", "OR")
keywords.set("print", "PRINT")
keywords.set("return", "RETURN")
keywords.set("super", "SUPER")
keywords.set("this", "THIS")
keywords.set("true", "TRUE")
keywords.set("var", "VAR")
keywords.set("while", "WHILE")
keywords.set("in", "IN")
